version: '3'
services:
  mongo:
    image: mongo:3.4.10
    environment:
      - MONGO_INITDB_ROOT_USERNAME:ms-username-dev
      - MONGO_INITDB_ROOT_PASSWORD:ms-password-dev
    ports:
      - "27017:27017"
    volumes:
      - /mnt/data/mongo:/data/db
    command: mongod
  configserver:
    image: zandolsi/ms-config-server:git-config-encrypted
    environment:
      ENCRYPT_KEY: "1bb7d069-4c5c-483f-a1dd-423cce61fb9e"
    ports:
      - "9090:9090"

  establishmentservice:
    image: zandolsi/ms-establishment:external-config-refresh-encrypted
    environment:
      SPRING_PROFILES_ACTIVE: default
      ENCRYPT_KEY: "1bb7d069-4c5c-483f-a1dd-423cce61fb9e"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - configserver