server:
  port: 9090
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/AndolsiZied/configuration-repo/
          searchPaths: establishment-services
          timeout: 30