eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discoveryserver:9191/eureka/

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false